version: '3.6'

services:
    nginx:
        image: nginx:stable
        volumes:
          - ${PWD}/nginx/app.conf:/etc/nginx/conf.d/default.conf
          - ${PWD}/src:/var/www/html
        ports:
          - 80:80
        environment:
          - "NGINX_HOST=${NGINX_HOST}"
    fpm:
        build: fpm
        user: "1000"
        ports:
          - 1337:1337
        volumes:
          - ${PWD}/src:/var/www/html
        environment:
          - "XDEBUG_CONFIG=${XDEBUG_CONFIG}"
          - "PHP_IDE_CONFIG=${PHP_IDE_CONFIG}"
          - "COMPOSER_MEMORY_LIMIT=-1"
