controllers:
  resource: ../src/Controller/
  type: annotation

#api_doc:
#  path: /api/doc
#  controller: Nelmio\ApiDocBundle\Controller\SwaggerUiController::indexAction
#app.swagger_ui:
#  path: /api/doc
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }